version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: doctrine/coding-standard
    versions:
    - "> 6.0"
  - dependency-name: vimeo/psalm
    versions:
    - "> 3.10"
